phases:
  - name: tests
    stages:
      - test1
      - test2

stages:
  - name: test1
    steps:
      - dir("."){sh "ls -la"}
      - script { echo "test" }
  - name: test2
    steps:
      - ezLog.info "info"
      - script { 
                  def sum=1+1;
                  echo "${sum}";
               }
